[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=UTF-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=UTF-8"

[[redirects]]
  from = "/*"
  to = "./index.html"
  status = 200
